name: Jekyll site CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.92.0
    - name: Exec jekyll build
      run: bundle exec jekyll build
